[package]
name = "biu_switch"
version = "1.0.0"
authors = ["Jia Ye <planet0104@gmail.com>"]
edition = "2021"

[dependencies]
embedded-hal = "1.0.0"
cortex-m = { version = "0.7.7", features = ["critical-section-single-core"] }
cortex-m-rt = "0.7.5"
# Panic behaviour, see https://crates.io/keywords/panic-impl for alternatives
panic-semihosting = "0.6.0"
cortex-m-semihosting = "0.5.0"

stm32f4xx-hal  = { version = "0.22.1", features = ["stm32f401"]}
embedded-storage = "0.3"
# stm32_i2s_v12x = "0.5.1"

[profile.dev]
#debug = true
lto = true
#opt-level = "s"

[profile.release]
lto = true
strip = true
opt-level = 's'
panic = 'abort'
codegen-units = 1